<?php

$html = file_get_contents('1.html');				// 1.html is generated by curl https://www.ptt.cc/hotboard.html > 1.html
$html = iconv('big5', 'utf-8//IGNORE', $html);			// transfer big5 to utf-8
$html = str_replace('charset=big5', 'charset=utf-8', $html);	

$output = fopen('php://output', 'w');

$doc = new DOMDocument();
@$doc->loadHTML($html);						// add @ to igore the warning message
$tag_TRs = $doc->getElementsByTagName('tr');

foreach ($tag_TRs as $tag_TR) {

  $tag_TDs = $tag_TR->getElementsByTagName('td');

  $hits   = explode('：', $tag_TDs->item(0)->nodeValue)[1];
  $ebName = $tag_TDs->item(1)->nodeValue;
  $cbName = $tag_TDs->item(2)->nodeValue;

  fputcsv($output, array($ebName, $hits, $cbName));		// format $output as csv
}
