<?php

$html = file_get_contents('2.html');			// 2.html is generated by curl http://axe-level-1.herokuapp.com/ > 2.html

$doc = new DOMDocument();	
@$doc->loadHTML($html);					// add @ to igore the warning message

$row = 1;
$json_content=array();
$tag_TRs = $doc->getElementsByTagName('tr');

foreach ($tag_TRs as $tag_TR) {

  if ($row++ == 1) {
    continue;   
  }

  $tag_TDs = $tag_TR->getElementsByTagName('td');

  $name = $tag_TDs->item(0)->nodeValue;
  $cls1 = intval($tag_TDs->item(1)->nodeValue);		// use intval to return a integer value
  $cls2 = intval($tag_TDs->item(2)->nodeValue);
  $cls3 = intval($tag_TDs->item(3)->nodeValue);
  $cls4 = intval($tag_TDs->item(4)->nodeValue);
  $cls5 = intval($tag_TDs->item(5)->nodeValue);

  $score = array();
  $score['國語'] = $cls1;
  $score['數學'] = $cls2;
  $score['自然'] = $cls3;
  $score['社會'] = $cls4;
  $score['健康教育'] = $cls5;

  $content = array();
  $content['name'] = $name;
  $content['grades'] = $score;

  $json_content[] = $content;
}

echo json_encode($json_content);			// encode data to json format via json_encode
