<?php

$html = file_get_contents('4-1.html');				// 1.html is generated by curl https://www.ptt.cc/bbs/mobilecomm/index.html > 4-1.html
$home = "https://www.ptt.cc";

$doc = new DOMDocument();
@$doc->loadHTML($html);						// add @ to igore the warning message

$output = fopen('php://output', 'w');

foreach ($doc->getElementsByTagName('div') as $tag_DIV) {

  if ($tag_DIV->getAttribute('class') != 'r-ent') {
    continue;
  }

  foreach ($tag_DIV->getElementsByTagName('div') as $DIV_rent) {
  
    $clsValue = $DIV_rent->getAttribute('class');
    
    if ($clsValue == 'title') {
      $title = trim($DIV_rent->nodeValue);
      $tag_A =  $DIV_rent->getElementsByTagName('a')->item(0);
      if (!empty($tag_A)) {
        $link = $home . $tag_A->getAttribute('href');
      }
    } else if ($clsValue == 'meta') {
      $DIV_metas = $DIV_rent->getElementsByTagName('div');
      $date   = trim($DIV_metas->item(0)->nodeValue);
      $author = $DIV_metas->item(1)->nodeValue;
    }

  }

  fputcsv($output, array($link, $title, $author, $date));	// format $output as csv
}
